apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dockerK8-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-docker-app
  template:
    metadata:
      labels:
        app: my-docker-app
    spec:
      containers:
        - name: my-dockerK8
          image: anijames/my-dockerk8-img:latest
          ports:
            - containerPort:8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  selector:
    app: my-docker-app
